#! /bin/sh
OUTPUT_DEV="/dev/mtdblock2"
DATA_DEV="/dev/mtdblock5"
SCRATCH_DEV="/dev/mtdblock4"
PREV_OUTPUT_CID_BLOCKDEV="/dev/mtdblock3"
METADATA_DEV="/dev/mtdblock6"
EMPTY_CID="bafybeiczsscdsbs7ffqz55asqdf3smv6klcw3gofszvwlyarci47bgf354"
EMPTY_SHA256="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

if [ "$RUNTIME_CONFIG" = "qemu" ]; then
  ARCH=amd64
else
  ARCH=riscv64
  RUNTIME_CONFIG=riscv64
fi

ARCH_PATH="/opt/$ARCH/bin"

echo "====================== TOSI STANDARD LOADER ========"
echo

export HOME=/root

echo "Mounting tmpfs on /mnt"
mount -t tmpfs tmpfs /mnt
echo "Mounting tmpfs on /root"
mount -t tmpfs tmpfs /root
echo "Mounting tmpfs on /tmp"
mount -t tmpfs tmpfs /tmp

if [ "$RUNTIME_CONFIG" = "qemu" ]; then
  OUTPUT_DEV="/dev/vdb"

  echo "Formatting scratch filesystem..."
  mke2fs -q -t ext2 -L scratch "/dev/vdd"

  mkdir "/mnt/scratch"
  mount "/dev/vdd" "/mnt/scratch"
  PREV_OUTPUT_CID_BLOCKDEV="/dev/vdc"
  DATA_DEV="/dev/vde"
  METADATA_DEV="/dev/vdf"
else
  echo "Formatting scratch filesystem..."
  mke2fs -q -t ext2 -L scratch "$SCRATCH_DEV"
  mkdir "/mnt/scratch"
  mount $SCRATCH_DEV /mnt/scratch
fi

# State overlay mountpoints and output directories.
echo "Bind mounting chroot code environment..."

PREV_OUTPUT_CID=$($ARCH_PATH/car root $PREV_OUTPUT_CID_BLOCKDEV)
INPUT_CID=$($ARCH_PATH/car root $DATA_DEV)

if [ x$PREV_OUTPUT_CID == xbafybeiczsscdsbs7ffqz55asqdf3smv6klcw3gofszvwlyarci47bgf354 ]; then
	echo "Empty state, picking input as our stage 2"
	STAGE2_DRIVE=$DATA_DEV
else
	STAGE2_DRIVE=$PREV_OUTPUT_CID_BLOCKDEV
fi

cd /mnt/scratch
$ARCH_PATH/car x -f $STAGE2_DRIVE --path boot/stage2.squashfs 

mkdir -p /mnt/stage2
mount -o ro /mnt/scratch/boot/stage2.squashfs /mnt/stage2
mount --bind /dev  /mnt/stage2/dev
mount --bind /proc /mnt/stage2/proc
mount --bind /sys  /mnt/stage2/sys
mkdir -p /mnt/scratch/root
mount --bind /mnt/scratch/root /mnt/stage2/root

chroot /mnt/stage2 /init $RUNTIME_CONFIG $PREV_OUTPUT_CID_BLOCKDEV $DATA_DEV $OUTPUT_DEV $METADATA_DEV

RET=$?
if [ x$RET != 0 ]; then
	echo "Something went wrong in stage2, return code $RET, returning previous output CID"
	printf "%s\0%s\0" $EMPTY_CID $EMPTY_SHA256 > /tmp/pre-sha256
	SHA256=$(sha256sum /tmp/pre-sha256 | cut -d " " -f -1)
	echo -n $SHA256 | xxd -r -p > $OUTPUT_DEV
	cp /empty.car /mnt/scratch/root/output.car
fi

echo "Done, halting..."

/bin/sync

if [ "$RUNTIME_CONFIG" = "qemu" ]; then
  exec /sbin/reboot -f
else 
  exec /sbin/halt -f
fi
